#!/bin/bash
CURRPWD=`dirname "$0"`
if [[ -e "$CURRPWD/source/ISDEV.sh" ]]; then
    source "$CURRPWD/source/ISDEV.sh"
fi
EXP_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
EXPERIMENT="catFR"
EXPERIMENT_NUM="1"
EXPERIMENT_DIR="RAM_$EXPERIMENT"
CONFIG="config.py"
SCONFIG="catFR1_config.py"

DOLOG=1

export PYTHONPATH=$PYTHONPATH:$HOME/RAM_2.0/source/pylib

ARCHIVE_DIR="./data/${EXPERIMENT}${EXPERIMENT_NUM}/"
RESOLUTION="1440x900"
NOFS=1
LOGS_DIR="./logs"
LOG_FILE="$LOGS_DIR/${EXPERIMENT}${EXPERIMENT_NUM}.log"

cd $EXP_DIR
mkdir -p $LOGS_DIR

echo "****************************************">>$LOG_FILE
date >> $LOG_FILE 



if [[ $SCONFIG != "" ]]; then
    SCONFIG_OPTION="--sconfig=$SCONFIG"
fi

if [[ "$NOFS" == "1" ]]; then
    NOFS_OPTION="--no-fs"
fi



# GET THE SUBJECT 

while [[ $SUBJ_NUM == "" ]]; do
    echo "ENTER SUBJECT CODE (subject codes containing \"test\" will not be recorded): "
    read SUBJ_NUM
done


if [[ $SUBJ_NUM =~ .*test.* ]]; then
    ARCHIVE_DIR="$HOME/test_data"
    rm -rf $ARCHIVE_DIR
fi
mkdir -p $ARCHIVE_DIR

OPTIONS="-s $SUBJ_NUM --config=$CONFIG $SCONFIG_OPTION --resolution=$RESOLUTION $NOFS_OPTION --archive=$ARCHIVE_DIR"

# RUNNING THE ACTUAL EXPERIMENT

echo $SUBJ_NUM >> $LOG_FILE

if [[ "$DOLOG" == "1" ]]; then
    python $EXPERIMENT.py $OPTIONS 2>&1 | tee -a $LOG_FILE
else
    python $EXPERIMENT.py $OPTIONS 
fi

if [[ -e $HOME/test_data ]]; then 
    rm -rf $HOME/test_data
fi

echo "Finised. Press any key to exit"; 
read
